Catkin-ProjectName: capture
Version: 0.2.3
Description: Capture is a set of tools to capture objects in 3D
Author: Ethan Rublee <erublee@willowgarage.com>, Vincent Rabaud <vrabaud@willowgarage.com>
Maintainer:  Vincent Rabaud <vrabaud@willowgarage.com>
Homepage:  http://ecto.willowgarage.com/recognition

Depends: catkin, boost, ecto, object_recognition_core

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake
